Demo 1 - API Calls and Footprint Rendering
GeoSTAC/CartoCosmos-with-STAC pull request #9
Opened 2022-01-13 21:44 UTC by amystamile

This is code from December Demo that displays footprints for Europa and Mars.

2022-01-16 22:56 UTC, gsn9 approved these changes
Looks good to me :)

2022-01-16 22:56 UTC, gsn9 commented on app/src/js/ApiJsonCollection.js
> +
This looks good to me, just an idea that might make our lives easier later on. Do we want to create a way to verify that we got a valid STAC Catalog from the API? It might be helpful for both tests and debugging if we need to.

2022-01-16 23:08 UTC, merged

2022-01-16 23:23 UTC, jrc632 requested changes
I would rather not have explicit comparisons with the names of the planetary bodies (like == "Mars").  Can we set these up as constants or a list of constants somehow?  Or maybe a dictionary-like data structure to tie specific STAC catalogs, titles, etc. with their respective planetary bodies.

Explicit Comparisons in the code:
app/src/js/ApiJsonCollection.js, lines 9, 21, 52, 64
app/src/js/AstroMap.js, line 94

2022-01-17 00:15 UTC, amystamile commented
> I would rather not have explicit comparisons with the names of the planetary bodies (like == "Mars"). Can we set these up as constants or a list of constants somehow? Or maybe a dictionary-like data structure to tie specific STAC catalogs, titles, etc. with their respective planetary bodies.
> 
> Explicit Comparisons in the code: app/src/js/ApiJsonCollection.js, lines 9, 21, 52, 64 app/src/js/AstroMap.js, line 94

Just to keep us moving on the code, I am okay leaving the comparisons as is. It was also noted by our client that it is okay to have these "hard-coded" for now. Please put up an issue regarding this, and if we have time, I think it would be worth revisiting this to clean up the code.